spring:

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc:mysql://114.132.40.5:3306/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    # jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://114.132.40.5:3306/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    #2017yyds  2017YYds,
    password: 2017YYds,

    hikari:
      #链接池名
      pool-name: DataHiKariCP
      #最小空闲连接数
      minimum-idle: 5
      #最大连接数
      maximum-pool-size: 10
      #空闲链接存活最大时间
      idle-timeout: 1800000
      #从连接池返回的链接自动提交
      auto-commit: true
      #链接最大存活时间
      max-lifetime: 1800000
      #链接超时时间
      connection-timeout: 30000
      #测试链接是否可用的查询语句
      connection-test-query: SELECT 1

  rabbitmq:
    host: 192.168.206.133
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        # 消费的最小数量
        concurrency: 10
        # 消费的最大数量
        max-concurrency: 10
        # 限制消费者每次只消费一条消息，处理完再继续下一条
        prefetch: 1
        # 启动时是否默认启动容器
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试最大时间
        initial-interval: 1000ms
        # 重试最大次数
        max-attempts: 3
        # 重试最大时间间隔
        max-interval: 10000ms
        # 重试的时间间隔倍数
        multiplier: 1

  redis:
    host: 192.168.206.132
    port: 6379
    database: 0
    password: eddie
    #链接超时时间
    connect-timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大链接阻塞时间
        max-wait: 10000ms
        #最大空闲链接
        max-idle: 200
        #最小空闲链接
        min-idle: 0

  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true

mybatis-plus:
  type-aliases-package: com.ms.seckill.pojo
  mapper-locations: classpath*:/mapper/*.xml
logging:
  level:
    com.ms.seckill.mapper: debug
